# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 12-20 * * 1-5'

permissions:
  contents: write

jobs:
  build:
    environment: TelegramBot
    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ vars.TELEGRAM_CHAT_ID }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        python scraper.py
    - name: Commit and push if it new rates are observed
      run: |-
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add --all
        timestamp=$(TZ=America/New_York date)
        git commit -m "Latest change: ${timestamp}" || exit 0
        git push
